[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "groggy"
description = "High-performance graph analytics with unified storage views - seamless integration between graph topology and advanced tabular operations"
version = "0.4.0"
requires-python = ">=3.8"
dependencies = [
    "networkx>=2.8",
]
authors = [
    {name = "Groggy Contributors", email = "contributors@groggy.dev"},
]
keywords = ["graph", "network", "memory-optimization", "version-control"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9", 
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Rust",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-benchmark>=4.0",
    "numpy>=1.20",  # For compatibility with ML workflows
    "networkx>=2.8",  # For comparison testing
]

[tool.maturin]
python-source = "python"
module-name = "groggy._groggy"
